import './burger.js';
import './explanation.js';
import './price.js';
import './services.js';
import './works.js';
import './faq.js';
import './form.js';
import './validation.js';
import './cockies-close.js';